[package]
name = "adventuria_real_xp"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.4.5"
godot_tokio = {git = "https://github.com/ShadowDash2000/godot_tokio"}
